version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: image-studio
    networks:
      - nano-banana-net
    ports:
      - "51130:51130"
    volumes:
      - ./server/config/app.config.json:/app/server/config/app.config.json
      - ./server/gallery:/app/server/gallery
      - ./server/data:/app/server/data

networks:
  nano-banana-net:
    driver: bridge
